--- #YAML:1.0
name:               Text-CSV
version:            1.17
abstract:           comma-separated values manipulator (using XS or PurePerl)
author:
    - Makamaka Hannyaharamitu, E<lt>makamaka[at]cpan.orgE<gt>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Handle:     0
    Test::Harness:  0
    Test::More:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
